pipeline {
  agent {
    kubernetes {
      yamlFile 'kubernetes/pod.yaml'
    }
  }
  stages {
    stage('Run debian') {
      steps {
        sh 'set'
        sh "echo OUTSIDE_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}"
        container('debian') {
          sh "echo DEBIAN_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}"
          sh 'uname -a'
        }
      }
    }
  }
}
